In [2]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
abhi = arr.copy()

In [10]:
abhi

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr.itemsize

4

In [23]:
arr.shape

(2, 3)

In [24]:
arr.ndim

2

In [25]:
arr.size

6

In [26]:
arr.dtype

dtype('int32')

In [3]:
arr2 = np.ones((5,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
arr2.dtype

dtype('float64')

In [29]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,20,5) #(Start, Stop, Number of elements)

array([ 0.,  5., 10., 15., 20.])

In [14]:
np.arange(0,20,1) #(Start, Stop, Steps)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])