## Demo: Matrix Product

In this demo, you will be shown how to implement Hill Cipher using matrix product.

### Question1: Perform Hill Cipher using matrix product

#### Description about Hill Cipher

'''
Hill Cipher is a polygraphic substitution cipher based on linear algebra.
Here the plain text is converted into encrypted form.
Each letter of plain text is represented by a number modulo 26.
Often the simple scheme A=0, B=1,....Z=25 is used
To encrypt a message, each block of n letters is multiplied by an invertible n × n matrix, against modulus 26
The matrix used for encryption is the cipher key, and it should be chosen randomly
Lets us take plain text = edurek and cipher key = [11 9
                                                     8 17]
Plain text is converted into 2×1 matrix format i.e. [e d] [u r] [e k]
Again plain text is converted into numbers i.e. [4 3] [20 11] [4 10]
So, encryption of hill cipher = (each column of plain text)*(key)*mod 26
'''

### Step 1: Import the libraries

In [1]:
import numpy as np

### Step 2: Create numpy array a as first column of plain text and array b as key

In [2]:
a = np.array([4,3])# e d
b= np.array([[11,9],[8,17]]) #key

In [4]:
b.ndim

2

In [5]:
c = a * b

In [6]:
c

array([[44, 27],
       [32, 51]])

### Step 3: Perform matrix product between array a and b

In [7]:
c=np.dot(a,b)

### Step 4: Perform encryption of plain text using mod function

In [8]:
c

array([68, 87])

In [21]:
87 % 26

9

In [23]:
h = np.mod(c,26)
print("h=",h) #encrypted

h= [[16  9]]


### Step 5: Create numpy array d of second column of plain text and array b as key

In [24]:
d = np.array([20,11]) # u r

In [26]:
d

array([20, 11])

### Step 6: Perform matrix product between array d and b

In [27]:
f = np.dot(d,b)

In [28]:
f

array([308, 367])

### Step 7: Perform encyption of plain text using mod function

In [29]:
h1=np.mod(f,26)
print("h1=",h1)

h1= [22  3]


### Step 8: Create a numpy array g of last column of plain text and array b as key

In [30]:
g = np.array([4,10]) # e k

### Step 9: Perform matrix product between array g and b

In [31]:
j =np.dot(g,b) 

### Step 10: Perform encyption of plain text using mod function

In [32]:
h2=np.mod(j,26) 
print("h2",h2)

h2 [20 24]


In [33]:
h , h1,h2

(array([[16,  9]], dtype=int32),
 array([22,  3], dtype=int32),
 array([20, 24], dtype=int32))

Represent the matrix h, h1, h2 in alphabetic manner as explained above. So Plain Text in encypted format will be qjwduy

#### Conclusion: This code demonstrates how to perform matrix product