## Numpy

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(0,100,(4,4))

In [ ]:
arr1

array([[64,  6, 90, 14],
       [ 6, 94, 80, 87],
       [60, 20, 46, 92],
       [95, 37, 30, 80]])

### Indexing

In [ ]:
arr1[0]

array([64,  6, 90, 14])

In [ ]:
arr1[2]

array([60, 20, 46, 92])

In [ ]:
arr1[1,3]

87

In [ ]:
arr1[2,2]

46

### Slicing

In [ ]:
arr1

array([[64,  6, 90, 14],
       [ 6, 94, 80, 87],
       [60, 20, 46, 92],
       [95, 37, 30, 80]])

In [ ]:
arr1[1:3]

array([[ 6, 94, 80, 87],
       [60, 20, 46, 92]])

In [ ]:
arr1[1:3,1:4]

array([[94, 80, 87],
       [20, 46, 92]])

### Fancy Indexing

In [ ]:
arr1

array([[64,  6, 90, 14],
       [ 6, 94, 80, 87],
       [60, 20, 46, 92],
       [95, 37, 30, 80]])

In [ ]:
arr1[[1,0,3]]

array([[ 6, 94, 80, 87],
       [64,  6, 90, 14],
       [95, 37, 30, 80]])

### iterator

In [ ]:
for x in np.nditer(arr1):
    print(x)

64
6
90
14
6
94
80
87
60
20
46
92
95
37
30
80
