##Day 7 - DIY Solution

**Q1. Problem Statement: Understanding Array Functions**

Write a Python program that takes the speeds of any vehicle to store it in a NumPy array and calculates the average speed.

**Note:** Use NumPy functions to get the desired output.


In [ ]:
#Numpy arrays- Calculating mean of array elements
import numpy

my_array = []
a = int(input("What number of speeds you want to enter?"))
for i in range(a):
    my_array.append(float(input("Enter the speeds in Km/hr: ")))
my_array = numpy.array(my_array)
mean = sum(my_array)//len(my_array)
print("The Average speed is:", mean, "Km/hr")

What number of speeds you want to enter?3
Enter the speeds in Km/hr: 45
Enter the speeds in Km/hr: 50
Enter the speeds in Km/hr: 37
The Average speed is: 44.0 Km/hr


**Q2. Problem Statement: Array Indexing/Slicing**

Write a Python program to generate a 3-D array with integers of your choice, perform indexing, and print the first two rows and last two columns of the array.

**Note:** Use NumPy arange() function to generate a random array.


In [2]:
#Slicing ndarray
import numpy as np

a = np.arange(20).reshape((5,4))

#printing the array
print("The array is:")
print(a)

# Select first two rows
print("The first two rows are:")
print(a[[0, 1], :])
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [12, 13, 14, 15]])

#Select first two columns
print("The last two coloumns are:")
print(a[:,[-2, -1]])


The array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The first two rows are:
[[0 1 2 3]
 [4 5 6 7]]
The last two coloumns are:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
