In [1]:
import numpy as np

In [2]:
x = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.shape

(3, 3)

In [5]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
x = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(x)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr.shape

(4, 3)

In [8]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
np.reshape(arr,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [13]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [14]:
arr.ravel() # 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
# Tranpose
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.transpose(arr)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [19]:
arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [20]:
x = np.array([1,2])
x.shape

(2,)

In [21]:
y = np.expand_dims(x,axis=0)
y.shape

(1, 2)

In [22]:
z = np.expand_dims(x,axis=1)
z.shape

(2, 1)

In [23]:
# Squeeze
x = np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [24]:
a = np.squeeze(x,axis=0)
a.shape

(3, 1)