In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

In [3]:
a.shape

(2, 2)

In [4]:
b.shape

(2,)

In [5]:
b = np.array([[5,6]])
b.shape

(1, 2)

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
b

array([[5, 6]])

In [12]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [19]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [23]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [25]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]