##Day 8 - DIY Solution

**Q1. Problem Statement: Understanding NumPy Array Functions - I**

Define a NumPy array with 4 * 5 dimensions, swap the array's dimensions to make it 5 * 4 using suitable functions.


In [ ]:
#Array manipulation(reshape and transpose)
import numpy as np
a = np.arange(20)
print("Original Array:")
print(a)
#Printing Reshape result
b = a.reshape((5,4))
print("Reshaped Array:")
print(b)
#Printing Transpose result
c = a.transpose()
print("Transpose of Array:")
print(b)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Transpose of Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


**Q2. Problem Statement: Understanding NumPy Array Functions - II**

Write a Python program to create two 2-dimensional arrays and apply hstack(), vstack(), concatenate(), and split() functions.


In [ ]:
#Slicing and Joining arrays
import numpy as np
a = np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print("First array is:")
print(a)
print("Second array is:")
print(b)
print("Applying hstack() function:")
arr1 = np.hstack((a, b))
print(arr1)
print("Applying vstack() function:")
arr2 = np.vstack((a, b))
print(arr2)
print("Applying concatenate() function:")
arr3 = np.concatenate((a, b))
print(arr3)
print("Applying split() function:")
arr4 = np.array_split(arr1, 2)
print(arr4)

First array is:
[[1 2]
 [3 4]]
Second array is:
[[6 7]
 [8 9]]
Applying hstack() function:
[[1 2 6 7]
 [3 4 8 9]]
Applying vstack() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying concatenate() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying split() function:
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
